# Google App Engine configuration
runtime: python311

instance_class: F2

entrypoint: gunicorn -b :$PORT app.main:app -c gunicorn.conf.py

env_variables:
  APP_NAME: "AI Agent Toolbox"
  APP_VERSION: "1.0.0"
  DEBUG: "False"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
